services:
  mongodb:
    image: mongo:latest
    container_name: astas_db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=emozoarg  
      - MONGO_INITDB_ROOT_PASSWORD=L1bVqyEhSAoOJXQJ 
      - MONGO_INITDB_DATABASE=cine 

volumes:
  mongodb_data:
    driver: local
